### ISSUE TITLE
Rewards API documentation

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps-rewards-android#38]
### Reason

Define the top level API for user interaction

### Description

The Rewards API needs to be defined and documented to simplify the integration with Capture Receipt and Kard API.

It should work as a singleton to simplify the integration.

Based in the current UI, the API require definitions for:

- Rewards.start
- Rewards.license
- Rewards.estimate
- Rewards.terms
- Rewards.earnings
- Rewards.availableAccounts
- AccountCommon
- Account
- Rewards.decline
- Rewards.login
- Rewards.logout
- Rewards.accounts

Check tiki/apps/issues/20 issues for the definition of each scenario. More methods/classes can be added as needed.

### Success Criteria

- [x] The classes, methods signatures and properties definitions
- [x] Class diagram
- [x] Documentation
- [x] Readme documentation

**Comment by Schuler-Gabriel** [comment]
the class diagram:
### Class Diagram

#### Rewards
- **Properties**
  - `accounts: MutableList<Account>`
  - `isLicensed: Boolean`
  - `colorScheme: ColorScheme`
  - `fontFamily: FontFamily`
- **Methods**
  - `start(...)`
  - `checkLicense()`
  - `createLicense()`
  - `declineLicense()`
  - `estimate(): OfferEstimate`
  - `monthlyEarnings(): List<MoreContributor>`
  - `earnings(): HomeEarnings`
  - `terms(): String`
  - `scan(...)`
  - `offers(provider: AccountCommon): List<Offer>`
  - `accounts(): List<Account>`
  - `accounts(accountCommon: AccountCommon): List<Account>`
  - `uncAccounts(): List<AccountCommon>`
  - `login(account: Account)`
  - `logout(account: Account)`

#### Account
- **Properties**
  - `isVerified: Boolean`
  - `accountCommon: AccountCommon`
  - `username: String`
  - `password: String`

#### AccountCommon
- **Enumerated Values**
  - `GMAIL`
  - `WALMART`
  - `UBER_EATS`
  - `TACO_BELL`
  - `DOLLAR_GENERAL`

#### OfferEstimate
- **Properties**
  - `minimumValue: Int`
  - `maximumValue: Int`

#### HomeEarnings
- **Properties**
  - `totalEarnings: Double`
  - `userRating: Double`
  - `maxEarning: Double`

#### MoreContributor
- **Properties**
  - `contributorName: String`
  - `contributionPercentage: Float`

#### Offer
- **Properties**
  - `provider: AccountCommon`
  - `offerDescription: String`
  - `offerLink: String`
